# -*- coding: utf-8 -*-
"""train_qwen_qlora_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106B-u5GbSV13BOgF6bWtZ8tk_C_DH2Yk

# **Cài Thư Viện**
"""

!pip install -U transformers datasets peft trl accelerate bitsandbytes sentencepiece

!pip install -U transformers datasets peft trl accelerate bitsandbytes sentencepiece

!pip install wandb

from google.colab import drive
drive.mount('/content/drive')

from datasets import load_dataset

data_files = {
    "train": "/content/drive/MyDrive/ai-bouquet/data/processed/customer_request_train.jsonl",
    "validation": "/content/drive/MyDrive/ai-bouquet/data/processed/customer_request_val.jsonl",
    "test": "/content/drive/MyDrive/ai-bouquet/data/processed/customer_request_test.jsonl",
}

dataset = load_dataset("json", data_files=data_files)

print(dataset)
print(dataset["train"][0])

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_name = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    trust_remote_code=True
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

model.config.use_cache = False

def formatting_prompts_func(example):
    messages = example["messages"]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

def formatting_prompts_func(example):
    text = tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

dataset = dataset.map(formatting_prompts_func)

print(dataset["train"][0]["text"])

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj"
    ],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/outputs/qwen2.5-3b-bouquet-extractor",
    num_train_epochs=5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    fp16=True,
    optim="paged_adamw_8bit",
    report_to="none",
)

from trl import SFTTrainer, SFTConfig

print(dataset.column_names)
print(dataset["train"][0])

def formatting_func(example):
    return {
        "text": example["text"]
    }

dataset = dataset.map(formatting_func)

print(dataset["train"].column_names)
print(dataset["train"][0]["text"])

sft_config = SFTConfig(
    output_dir="outputs",
    dataset_text_field="text",
    max_length=2048,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=1,
    learning_rate=2e-4,
    warmup_steps=5,
    logging_steps=1,
    optim="adamw_8bit",
    weight_decay=0.01,
    lr_scheduler_type="linear",
    seed=3407,
)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    args=sft_config,
)

trainer.train()

save_path = "/content/outputs/qwen2.5-3b-bouquet-extractor"

trainer.model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("Saved to:", save_path)

from peft import PeftModel

base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

tokenizer = AutoTokenizer.from_pretrained(save_path, trust_remote_code=True)

model = PeftModel.from_pretrained(base_model, save_path)
model.eval()

import json
import re

def extract_requirements(message):
    messages = [
        {
            "role": "system",
            "content": "You extract structured bouquet requirements from Vietnamese customer messages. Return only valid JSON."
        },
        {
            "role": "user",
            "content": message
        }
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    input_len = inputs["input_ids"].shape[1]

    outputs = model.generate(
        **inputs,
        max_new_tokens=256,
        do_sample=False,
        pad_token_id=tokenizer.eos_token_id
    )

    generated_ids = outputs[0][input_len:]

    result = tokenizer.decode(
        generated_ids,
        skip_special_tokens=True
    ).strip()

    match = re.search(r"\{.*\}", result, re.DOTALL)

    if match:
        result = match.group(0)

    return result

message = "Tôi cần một bó hoa có kèm cẩm tú cầu để tặng người bạn trong mức giá 500k đổ lại."

result = extract_requirements(message)

print(result)

model.save_pretrained("outputs/qwen2.5-3b-bouquet-extractor")
tokenizer.save_pretrained("outputs/qwen2.5-3b-bouquet-extractor")

